### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [pastukh77/homework0#1]
Документи що Ви оформляєте повинні бути написані діловою мовою. API надає дані для  системи PV а у вас просто дах? Ознайомтеся з можливостями сучасних систем проектування https://helpcenter.graphisoft.com/user-guide/77214/
Тема: Обчислення параметрів нагрівання даху сонячною енергією. (Обчислення параметрів даху для його максимального нагрівання сонячною енергією.)

**Comment by pastukh77** [comment]
Дякуємо за коментар.


Намагалися писати стилем, який був би, принаймні, наближеним до ділового -
надалі старатимемося краще.

Чи можемо ми обговорити з Вами тему дослідження? Початковою метою було
визначення перспектив, опираючись на вже обраховані параметри. Це означає,
що власне ми жодних параметрів не обчислюватимемо, а лише
використовуватимемо наявні та, так би мовити, систематизуватимемо їх для
визначення перспектив використання системи безпосередньо на якомусь дахові.

Обраховувати власне якісь параметри (напр. альбедо) не має змісту, оскільки
вже все є виведено різноманітними метеорологічними станціями.

Щодо АРІ, то його використання мало зміст при початковій темі, оскільки ми
використовували дану величину для того, щоб мати дані щодо сонячного
потоку, а він буде однаковим, що на простому дахові, що на PV (за
одинакових інших умов).


До речі,  ми так розуміємо, що Ви нас закріпили в парі, так?


Дякую за відповідь,

Ярослав

**Comment by anrom7** [comment]
В парі я Вас закріпив. Але тепер ще менше розумію що Ви збираєтесь робити. 
На вході у Вас є: 1) параметри сонячної активності 2) патент 3) конкретний дах (площа, нахил, орієнтація, теплоізоляція...) Що буде на виході: ? Характеристики які забезпечує цей дах? - що це за характеристики? температура нагрівання даху, температура в під даховому прострі

**Comment by yluchka** [comment]
На основі середньостатистичних даних: кількості сонячних днів у сезоні та ін., індивідуальних параметрів даху: площа, кут нахилу, матеріал (для альбедо), ми плануємо оцінити кількість можливої закумулюваної енергії протягом певного періоду часу (періоду міжсезоння: коли опалення приміщення вже потрібне, попри хорошу сонячну погоду). Також оскільки дану систему доцільно використовувати для великих сільськогосподарських приміщень, де не потрібна висока температура, то даний період може коригуватися і на зимовий час. 
Отже, на виході ми хочемо дати певні оціночні характеристики конкретного приміщення для купівлі даної системи (на основі параметрів нагрівання даху), щоб вказати на його перспективи.
Якщо питання стоїть у формулюванні теми, то Ваша тема найбільш наближено підходить нашій ідеї, якщо змінити перше слово "Обрахунок" на "Оцінка"

**Comment by anrom7** [comment]
Значить я все добре зрозумів. Оцінка ж робиться на основі якихось чисел? В наступних ДЗ буде видно як Ви виходите на цю оцінку.
